// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';
/**
 * @constructor
 */
export namespace ec_prv.fbs{
export class LookupRequest {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns LookupRequest
 */
__init(i:number, bb:flatbuffers.ByteBuffer):LookupRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param LookupRequest= obj
 * @returns LookupRequest
 */
static getRootAsLookupRequest(bb:flatbuffers.ByteBuffer, obj?:LookupRequest):LookupRequest {
  return (obj || new LookupRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param LookupRequest= obj
 * @returns LookupRequest
 */
static getSizePrefixedRootAsLookupRequest(bb:flatbuffers.ByteBuffer, obj?:LookupRequest):LookupRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new LookupRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns number
 */
version():number {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 1;
};

/**
 * @param number index
 * @returns number
 */
lookupKey(index: number):number|null {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
};

/**
 * @returns number
 */
lookupKeyLength():number {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @returns Uint8Array
 */
lookupKeyArray():Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startLookupRequest(builder:flatbuffers.Builder) {
  builder.startObject(2);
};

/**
 * @param flatbuffers.Builder builder
 * @param number version
 */
static addVersion(builder:flatbuffers.Builder, version:number) {
  builder.addFieldInt8(0, version, 1);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset lookupKeyOffset
 */
static addLookupKey(builder:flatbuffers.Builder, lookupKeyOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, lookupKeyOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param Array.<number> data
 * @returns flatbuffers.Offset
 */
static createLookupKeyVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]);
  }
  return builder.endVector();
};

/**
 * @param flatbuffers.Builder builder
 * @param number numElems
 */
static startLookupKeyVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endLookupRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset offset
 */
static finishLookupRequestBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset offset
 */
static finishSizePrefixedLookupRequestBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
};

static createLookupRequest(builder:flatbuffers.Builder, version:number, lookupKeyOffset:flatbuffers.Offset):flatbuffers.Offset {
  LookupRequest.startLookupRequest(builder);
  LookupRequest.addVersion(builder, version);
  LookupRequest.addLookupKey(builder, lookupKeyOffset);
  return LookupRequest.endLookupRequest(builder);
}

/**
 * @returns LookupRequestT
 */
unpack(): LookupRequestT {
  return new LookupRequestT(
    this.version(),
    this.bb!.createScalarList(this.lookupKey.bind(this), this.lookupKeyLength())
  );
};

/**
 * @param LookupRequestT _o
 */
unpackTo(_o: LookupRequestT): void {
  _o.version = this.version();
  _o.lookupKey = this.bb!.createScalarList(this.lookupKey.bind(this), this.lookupKeyLength());
};
}

export class LookupRequestT {
/**
 * @constructor
 * @param number version
 * @param (number)[] lookupKey
 */
constructor(
  public version: number = 1,
  public lookupKey: (number)[] = []
){};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const lookupKey = ec_prv.fbs.LookupRequest.createLookupKeyVector(builder, this.lookupKey);

  return ec_prv.fbs.LookupRequest.createLookupRequest(builder,
    this.version,
    lookupKey
  );
};
}
}
