// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';
/**
 * @constructor
 */
export namespace ec_prv.fbs{
export class ShorteningRequest {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns ShorteningRequest
 */
__init(i:number, bb:flatbuffers.ByteBuffer):ShorteningRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param ShorteningRequest= obj
 * @returns ShorteningRequest
 */
static getRootAsShorteningRequest(bb:flatbuffers.ByteBuffer, obj?:ShorteningRequest):ShorteningRequest {
  return (obj || new ShorteningRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param ShorteningRequest= obj
 * @returns ShorteningRequest
 */
static getSizePrefixedRootAsShorteningRequest(bb:flatbuffers.ByteBuffer, obj?:ShorteningRequest):ShorteningRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ShorteningRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns number
 */
version():number {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 1;
};

/**
 * @returns flatbuffers.Long
 */
expiry():flatbuffers.Long {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : this.bb!.createLong(0, 0);
};

/**
 * @returns number
 */
pbkdf2Iters():number {
  var offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
};

/**
 * @param number index
 * @returns number
 */
salt(index: number):number|null {
  var offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
};

/**
 * @returns number
 */
saltLength():number {
  var offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @returns Uint8Array
 */
saltArray():Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
};

/**
 * @param number index
 * @returns number
 */
iv(index: number):number|null {
  var offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
};

/**
 * @returns number
 */
ivLength():number {
  var offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @returns Uint8Array
 */
ivArray():Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
};

/**
 * @param number index
 * @returns number
 */
blindedUrl(index: number):number|null {
  var offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
};

/**
 * @returns number
 */
blindedUrlLength():number {
  var offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @returns Uint8Array
 */
blindedUrlArray():Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startShorteningRequest(builder:flatbuffers.Builder) {
  builder.startObject(6);
};

/**
 * @param flatbuffers.Builder builder
 * @param number version
 */
static addVersion(builder:flatbuffers.Builder, version:number) {
  builder.addFieldInt8(0, version, 1);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Long expiry
 */
static addExpiry(builder:flatbuffers.Builder, expiry:flatbuffers.Long) {
  builder.addFieldInt64(1, expiry, builder.createLong(0, 0));
};

/**
 * @param flatbuffers.Builder builder
 * @param number pbkdf2Iters
 */
static addPbkdf2Iters(builder:flatbuffers.Builder, pbkdf2Iters:number) {
  builder.addFieldInt32(2, pbkdf2Iters, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset saltOffset
 */
static addSalt(builder:flatbuffers.Builder, saltOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, saltOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param Array.<number> data
 * @returns flatbuffers.Offset
 */
static createSaltVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]);
  }
  return builder.endVector();
};

/**
 * @param flatbuffers.Builder builder
 * @param number numElems
 */
static startSaltVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset ivOffset
 */
static addIv(builder:flatbuffers.Builder, ivOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, ivOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param Array.<number> data
 * @returns flatbuffers.Offset
 */
static createIvVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]);
  }
  return builder.endVector();
};

/**
 * @param flatbuffers.Builder builder
 * @param number numElems
 */
static startIvVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset blindedUrlOffset
 */
static addBlindedUrl(builder:flatbuffers.Builder, blindedUrlOffset:flatbuffers.Offset) {
  builder.addFieldOffset(5, blindedUrlOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param Array.<number> data
 * @returns flatbuffers.Offset
 */
static createBlindedUrlVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]);
  }
  return builder.endVector();
};

/**
 * @param flatbuffers.Builder builder
 * @param number numElems
 */
static startBlindedUrlVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endShorteningRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset offset
 */
static finishShorteningRequestBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset offset
 */
static finishSizePrefixedShorteningRequestBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
};

static createShorteningRequest(builder:flatbuffers.Builder, version:number, expiry:flatbuffers.Long, pbkdf2Iters:number, saltOffset:flatbuffers.Offset, ivOffset:flatbuffers.Offset, blindedUrlOffset:flatbuffers.Offset):flatbuffers.Offset {
  ShorteningRequest.startShorteningRequest(builder);
  ShorteningRequest.addVersion(builder, version);
  ShorteningRequest.addExpiry(builder, expiry);
  ShorteningRequest.addPbkdf2Iters(builder, pbkdf2Iters);
  ShorteningRequest.addSalt(builder, saltOffset);
  ShorteningRequest.addIv(builder, ivOffset);
  ShorteningRequest.addBlindedUrl(builder, blindedUrlOffset);
  return ShorteningRequest.endShorteningRequest(builder);
}

/**
 * @returns ShorteningRequestT
 */
unpack(): ShorteningRequestT {
  return new ShorteningRequestT(
    this.version(),
    this.expiry(),
    this.pbkdf2Iters(),
    this.bb!.createScalarList(this.salt.bind(this), this.saltLength()),
    this.bb!.createScalarList(this.iv.bind(this), this.ivLength()),
    this.bb!.createScalarList(this.blindedUrl.bind(this), this.blindedUrlLength())
  );
};

/**
 * @param ShorteningRequestT _o
 */
unpackTo(_o: ShorteningRequestT): void {
  _o.version = this.version();
  _o.expiry = this.expiry();
  _o.pbkdf2Iters = this.pbkdf2Iters();
  _o.salt = this.bb!.createScalarList(this.salt.bind(this), this.saltLength());
  _o.iv = this.bb!.createScalarList(this.iv.bind(this), this.ivLength());
  _o.blindedUrl = this.bb!.createScalarList(this.blindedUrl.bind(this), this.blindedUrlLength());
};
}

export class ShorteningRequestT {
/**
 * @constructor
 * @param number version
 * @param flatbuffers.Long expiry
 * @param number pbkdf2Iters
 * @param (number)[] salt
 * @param (number)[] iv
 * @param (number)[] blindedUrl
 */
constructor(
  public version: number = 1,
  public expiry: flatbuffers.Long = flatbuffers.createLong(0, 0),
  public pbkdf2Iters: number = 0,
  public salt: (number)[] = [],
  public iv: (number)[] = [],
  public blindedUrl: (number)[] = []
){};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const salt = ec_prv.fbs.ShorteningRequest.createSaltVector(builder, this.salt);
  const iv = ec_prv.fbs.ShorteningRequest.createIvVector(builder, this.iv);
  const blindedUrl = ec_prv.fbs.ShorteningRequest.createBlindedUrlVector(builder, this.blindedUrl);

  return ec_prv.fbs.ShorteningRequest.createShorteningRequest(builder,
    this.version,
    this.expiry,
    this.pbkdf2Iters,
    salt,
    iv,
    blindedUrl
  );
};
}
}
