// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';
/**
 * @constructor
 */
export namespace ec_prv.fbs{
export class TrustedShorteningRequest {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns TrustedShorteningRequest
 */
__init(i:number, bb:flatbuffers.ByteBuffer):TrustedShorteningRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param TrustedShorteningRequest= obj
 * @returns TrustedShorteningRequest
 */
static getRootAsTrustedShorteningRequest(bb:flatbuffers.ByteBuffer, obj?:TrustedShorteningRequest):TrustedShorteningRequest {
  return (obj || new TrustedShorteningRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param TrustedShorteningRequest= obj
 * @returns TrustedShorteningRequest
 */
static getSizePrefixedRootAsTrustedShorteningRequest(bb:flatbuffers.ByteBuffer, obj?:TrustedShorteningRequest):TrustedShorteningRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new TrustedShorteningRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns number
 */
version():number {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 1;
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
url():string|null
url(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
url(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startTrustedShorteningRequest(builder:flatbuffers.Builder) {
  builder.startObject(2);
};

/**
 * @param flatbuffers.Builder builder
 * @param number version
 */
static addVersion(builder:flatbuffers.Builder, version:number) {
  builder.addFieldInt8(0, version, 1);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset urlOffset
 */
static addUrl(builder:flatbuffers.Builder, urlOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, urlOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endTrustedShorteningRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset offset
 */
static finishTrustedShorteningRequestBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset offset
 */
static finishSizePrefixedTrustedShorteningRequestBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
};

static createTrustedShorteningRequest(builder:flatbuffers.Builder, version:number, urlOffset:flatbuffers.Offset):flatbuffers.Offset {
  TrustedShorteningRequest.startTrustedShorteningRequest(builder);
  TrustedShorteningRequest.addVersion(builder, version);
  TrustedShorteningRequest.addUrl(builder, urlOffset);
  return TrustedShorteningRequest.endTrustedShorteningRequest(builder);
}

/**
 * @returns TrustedShorteningRequestT
 */
unpack(): TrustedShorteningRequestT {
  return new TrustedShorteningRequestT(
    this.version(),
    this.url()
  );
};

/**
 * @param TrustedShorteningRequestT _o
 */
unpackTo(_o: TrustedShorteningRequestT): void {
  _o.version = this.version();
  _o.url = this.url();
};
}

export class TrustedShorteningRequestT {
/**
 * @constructor
 * @param number version
 * @param string|Uint8Array|null url
 */
constructor(
  public version: number = 1,
  public url: string|Uint8Array|null = null
){};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const url = (this.url !== null ? builder.createString(this.url!) : 0);

  return ec_prv.fbs.TrustedShorteningRequest.createTrustedShorteningRequest(builder,
    this.version,
    url
  );
};
}
}
