// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';
/**
 * @constructor
 */
export namespace ec_prv.fbs{
export class TrustedLookupResponse {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns TrustedLookupResponse
 */
__init(i:number, bb:flatbuffers.ByteBuffer):TrustedLookupResponse {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param TrustedLookupResponse= obj
 * @returns TrustedLookupResponse
 */
static getRootAsTrustedLookupResponse(bb:flatbuffers.ByteBuffer, obj?:TrustedLookupResponse):TrustedLookupResponse {
  return (obj || new TrustedLookupResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param TrustedLookupResponse= obj
 * @returns TrustedLookupResponse
 */
static getSizePrefixedRootAsTrustedLookupResponse(bb:flatbuffers.ByteBuffer, obj?:TrustedLookupResponse):TrustedLookupResponse {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new TrustedLookupResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @returns number
 */
version():number {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 1;
};

/**
 * @returns boolean
 */
error():boolean {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
url():string|null
url(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
url(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startTrustedLookupResponse(builder:flatbuffers.Builder) {
  builder.startObject(3);
};

/**
 * @param flatbuffers.Builder builder
 * @param number version
 */
static addVersion(builder:flatbuffers.Builder, version:number) {
  builder.addFieldInt8(0, version, 1);
};

/**
 * @param flatbuffers.Builder builder
 * @param boolean error
 */
static addError(builder:flatbuffers.Builder, error:boolean) {
  builder.addFieldInt8(1, +error, +false);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset urlOffset
 */
static addUrl(builder:flatbuffers.Builder, urlOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, urlOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endTrustedLookupResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset offset
 */
static finishTrustedLookupResponseBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset offset
 */
static finishSizePrefixedTrustedLookupResponseBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
};

static createTrustedLookupResponse(builder:flatbuffers.Builder, version:number, error:boolean, urlOffset:flatbuffers.Offset):flatbuffers.Offset {
  TrustedLookupResponse.startTrustedLookupResponse(builder);
  TrustedLookupResponse.addVersion(builder, version);
  TrustedLookupResponse.addError(builder, error);
  TrustedLookupResponse.addUrl(builder, urlOffset);
  return TrustedLookupResponse.endTrustedLookupResponse(builder);
}

/**
 * @returns TrustedLookupResponseT
 */
unpack(): TrustedLookupResponseT {
  return new TrustedLookupResponseT(
    this.version(),
    this.error(),
    this.url()
  );
};

/**
 * @param TrustedLookupResponseT _o
 */
unpackTo(_o: TrustedLookupResponseT): void {
  _o.version = this.version();
  _o.error = this.error();
  _o.url = this.url();
};
}

export class TrustedLookupResponseT {
/**
 * @constructor
 * @param number version
 * @param boolean error
 * @param string|Uint8Array|null url
 */
constructor(
  public version: number = 1,
  public error: boolean = false,
  public url: string|Uint8Array|null = null
){};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const url = (this.url !== null ? builder.createString(this.url!) : 0);

  return ec_prv.fbs.TrustedLookupResponse.createTrustedLookupResponse(builder,
    this.version,
    this.error,
    url
  );
};
}
}
